# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from typing import Iterable as typing___Iterable
from typing import Optional as typing___Optional
from typing import Text as typing___Text

from google.protobuf.internal.containers import (
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)
from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing_extensions import Literal as typing_extensions___Literal

class WordCountRequest(google___protobuf___message___Message):
    uri = ...  # type: typing___Text
    words = ...  # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]

    def __init__(self,
                 uri: typing___Optional[typing___Text] = None,
                 words: typing___Optional[
                     typing___Iterable[typing___Text]] = None,
                 ) -> None:
        ...

    @classmethod
    def FromString(cls, s: bytes) -> WordCountRequest:
        ...

    def MergeFrom(self,
                  other_msg: google___protobuf___message___Message) -> None:
        ...

    def CopyFrom(self,
                 other_msg: google___protobuf___message___Message) -> None:
        ...

    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[
            u"uri", u"words"]) -> None:
            ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[
            b"uri", b"words"]) -> None:
            ...


class WordCount(google___protobuf___message___Message):
    word = ...  # type: typing___Text
    uri = ...  # type: typing___Text
    count = ...  # type: int

    def __init__(self,
                 word: typing___Optional[typing___Text] = None,
                 uri: typing___Optional[typing___Text] = None,
                 count: typing___Optional[int] = None,
                 ) -> None:
        ...

    @classmethod
    def FromString(cls, s: bytes) -> WordCount:
        ...

    def MergeFrom(self,
                  other_msg: google___protobuf___message___Message) -> None:
        ...

    def CopyFrom(self,
                 other_msg: google___protobuf___message___Message) -> None:
        ...

    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[
            u"count", u"uri", u"word"]) -> None:
            ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[
            b"count", b"uri", b"word"]) -> None:
            ...
